# Generated by Django 4.2 on 2023-05-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
