# Generated by Django 4.2 on 2023-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
    ]
